CARS = [
    {
        "id": "1",
        "make": "Toyota",
        "model": "Camry",
        "car-year": "2020",
        "vehicle-type": "Sedan",
        "transmission": "Auto",
        "Millage-included-KM": 150,
        "price": 45.99,
        "fuel-type": "Hybrid",
        "image-path": [
            "https://images.unsplash.com/photo-1502877338535-766e1452684a?q=80&w=2944&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
        ],
        "location": {
            "lat": "49.282729",
            "lng": "-123.120738",
            "city": "Vancouver",
            "country": "Canada",
        },
        "trips": {"avg-rate": 4.7, "trip-count": 34},
    },
    {
        "id": "2",
        "make": "Tesla",
        "model": "Model 3",
        "car-year": "2022",
        "vehicle-type": "Sedan",
        "transmission": "Auto",
        "Millage-included-KM": 200,
        "price": 89.99,
        "fuel-type": "Electric",
        "image-path": [
            "https://images.unsplash.com/photo-1617704548623-340376564e68?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
        ],
        "location": {
            "lat": "49.282729",
            "lng": "-123.120738",
            "city": "Vancouver",
            "country": "Canada",
        },
        "trips": {"avg-rate": 4.9, "trip-count": 58},
    },
    {
        "id": "3",
        "make": "Ford",
        "model": "F-150",
        "car-year": "2019",
        "vehicle-type": "Truck",
        "transmission": "Manual",
        "Millage-included-KM": 100,
        "price": 59.99,
        "fuel-type": "Gas",
        "image-path": [
            "https://images.unsplash.com/photo-1605893477799-b99e3b8b93fe?q=80&w=2874&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
        ],
        "location": {
            "lat": "49.282729",
            "lng": "-123.120738",
            "city": "Vancouver",
            "country": "Canada",
        },
        "trips": {"avg-rate": 4.5, "trip-count": 22},
    },
]


CARS_EXTENDED = [
    {
        "id": "1",
        "make": "Toyota",
        "model": "Camry",
        "car-year": "2020",
        "vehicle-type": "Sedan",
        "transmission": "Auto",
        "Millage-included-KM": 150,
        "price": 45.99,
        "fuel-type": "Hybrid",
        "description": "A reliable and fuel-efficient sedan, perfect for city driving.",
        "image-path": [
            "https://images.unsplash.com/photo-1502877338535-766e1452684a?q=80&w=2944&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
        ],
        "location": {
            "lat": "49.282729",
            "lng": "-123.120738",
            "city": "Vancouver",
            "country": "Canada",
        },
        "trips": {"avg-rate": 4.7, "trip-count": 34},
        "Host": {
            "id": "host_001",
            "first-name": "John",
            "since": "2018-05-20",
            "image-path": "https://plus.unsplash.com/premium_photo-1683134080778-aaa686741d0a?q=80&w=3084&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
            "trips-count": 125,
            "avg-rate": 4.8,
        },
        "review": [
            {
                "id": "review_001",
                "user-id": "user_001",
                "createdAt": "2023-01-15",
                "name": "Alice",
                "comment": "Great car! Smooth ride and very clean.",
                "rate": 5.0,
                "host-reply": "Thank you, Alice! Glad you enjoyed the ride.",
            },
            {
                "id": "review_002",
                "user-id": "user_002",
                "createdAt": "2023-03-22",
                "name": "Bob",
                "comment": "The car was in excellent condition and very economical.",
                "rate": 4.5,
                "host-reply": "Thank you, Bob! Hope to see you again.",
            },
        ],
    },
    {
        "id": "2",
        "make": "Tesla",
        "model": "Model 3",
        "car-year": "2022",
        "vehicle-type": "Sedan",
        "transmission": "Auto",
        "Millage-included-KM": 200,
        "price": 89.99,
        "fuel-type": "Electric",
        "description": "A high-performance electric vehicle with autopilot features and a sleek design.",
        "image-path": [
            "https://images.unsplash.com/photo-1617704548623-340376564e68?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
        ],
        "location": {
            "lat": "49.282729",
            "lng": "-123.120738",
            "city": "Vancouver",
            "country": "Canada",
        },
        "trips": {"id": "trip_002", "avg-rate": 4.9, "trip-count": 58},
        "Host": {
            "id": "host_002",
            "first-name": "Sarah",
            "since": "2019-08-10",
            "image-path": "https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=3088&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
            "trips-count": 200,
            "avg-rate": 4.9,
        },
        "review": [
            {
                "id": "review_003",
                "user-id": "user_003",
                "createdAt": "2023-02-10",
                "name": "Charlie",
                "comment": "Amazing car with incredible features. Loved the autopilot!",
                "rate": 5.0,
                "host-reply": "Thank you, Charlie! Happy you enjoyed it.",
            },
            {
                "id": "review_004",
                "user-id": "user_004",
                "createdAt": "2023-04-18",
                "name": "Dana",
                "comment": "A great experience driving this Tesla. Highly recommend!",
                "rate": 4.8,
                "host-reply": "Thanks, Dana! Looking forward to your next trip.",
            },
        ],
    },
    {
        "id": "3",
        "make": "Ford",
        "model": "F-150",
        "car-year": "2019",
        "vehicle-type": "Truck",
        "transmission": "Manual",
        "Millage-included-KM": 100,
        "price": 59.99,
        "fuel-type": "Gas",
        "description": "A powerful and rugged truck, ideal for transporting goods and off-road adventures.",
        "image-path": [
            "https://images.unsplash.com/photo-1605893477799-b99e3b8b93fe?q=80&w=2874&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
        ],
        "location": {
            "lat": "49.282729",
            "lng": "-123.120738",
            "city": "Vancouver",
            "country": "Canada",
        },
        "trips": {"id": "trip_003", "avg-rate": 4.5, "trip-count": 22},
        "Host": {
            "id": "host_003",
            "first-name": "Mike",
            "since": "2017-11-25",
            "image-path": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=2864&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
            "trips-count": 150,
            "avg-rate": 4.7,
        },
        "review": [
            {
                "id": "review_005",
                "user-id": "user_005",
                "createdAt": "2023-01-30",
                "name": "Eve",
                "comment": "The truck was perfect for our camping trip. Very reliable.",
                "rate": 4.7,
                "host-reply": "Thanks, Eve! Glad it served you well.",
            },
            {
                "id": "review_006",
                "user-id": "user_006",
                "createdAt": "2023-03-12",
                "name": "Frank",
                "comment": "Great truck for moving large items. No issues at all.",
                "rate": 4.4,
                "host-reply": "Appreciate the feedback, Frank! Hope to see you again.",
            },
        ],
    },
]
